write errors to stderr

diff --git a/qubes-remote-support-receiver-start b/qubes-remote-support-receiver-start
--- a/qubes-remote-support-receiver-start
+++ b/qubes-remote-support-receiver-start
@@ -13,7 +13,7 @@ fi
 
 no_root_check() {
     if [ "$(id -u)" = "0" ]; then
-        echo "ERROR: Do not run $0 as root / with sudo!"
+        echo "ERROR: Do not run $0 as root / with sudo!" >&2
         exit 100
     fi
 }
@@ -102,7 +102,7 @@ dom0_rpc_policy_setup() {
 dom0_sshd_hardening() {
     local old new file_name
     if ! test -e /etc/ssh/sshd_config ; then
-        true "ERROR: file /etc/ssh/sshd_config does not exist!"
+        echo "ERROR: file /etc/ssh/sshd_config does not exist!" >&2
         exit 1
     fi
     ## dom0 minimal sshd configuration hardening
@@ -253,7 +253,7 @@ wormhole_send_wrapper() {
     done < <( $wormhole_tool "$temp_dir/remote-support-keys.tar.gz" 2>&1 )
 
     if [ "$found" = "no" ]; then
-        true "${red}${bold}ERROR: wormhole issue.${reset}"
+        echo "${red}${bold}ERROR: wormhole issue.${reset}" >&2
     fi
 }
 
diff --git a/qubes-remote-support-receiver-status b/qubes-remote-support-receiver-status
--- a/qubes-remote-support-receiver-status
+++ b/qubes-remote-support-receiver-status
@@ -19,7 +19,7 @@ trap error_handler ERR
 
 no_root_check() {
     if [ "$(id -u)" = "0" ]; then
-        echo "ERROR: Do not run $0 as root / with sudo!"
+        echo "ERROR: Do not run $0 as root / with sudo!" >&2
         exit 100
     fi
 }
@@ -36,9 +36,9 @@ dom0_check_rpc_policy() {
     if grep -q "$append_string" /etc/qubes-rpc/policy/qubes.ConnectTCP+22 ; then
         true "INFO: /etc/qubes-rpc/policy/qubes.ConnectTCP+22 looks OK."
     else
-        true "INFO: /etc/qubes-rpc/policy/qubes.ConnectTCP+22 missing line
+        echo "INFO: /etc/qubes-rpc/policy/qubes.ConnectTCP+22 missing line
 $append_string
-remote support will not work."
+remote support will not work." >&2
         exit 3
     fi
 }
diff --git a/qubes-remote-support-receiver-stop b/qubes-remote-support-receiver-stop
--- a/qubes-remote-support-receiver-stop
+++ b/qubes-remote-support-receiver-stop
@@ -9,7 +9,7 @@ fi
 
 no_root_check() {
     if [ "$(id -u)" = "0" ]; then
-        echo "ERROR: Do not run $0 as root / with sudo!"
+        echo "ERROR: Do not run $0 as root / with sudo!" >&2
         exit 100
     fi
 }
